---
plan_slug: standard-2
triggers:
- event: branch
  branch_name: main
- event: pull_request
commands:
- checkout
- neetoci-version ruby 3.2.2
- bundle install --deployment --path vendor/bundle
- bundle exec rspec
